### ISSUE TITLE
Problems with Rate limiting

### ISSUE THREAD

**Issue by whatwehaveunlearned** [VT-CHCI/google-scholar#2]
Hi first of all thank you for making the effort of developing this npm package.
I have been using it for a day without any problems but about an hour ago I began to experience an issue where the then function after scholar.search is not running and node Js is complaining about an unhandled promise rejection. Could this be that Google is blocking me from access and thats why I am not getting a response? Have you experienced this before?

Thank you.

**Comment by whatwehaveunlearned** [comment]
I guess its google blocking because it works when I change my IP.

**Comment by hcientist** [comment]
you're welcome! I'm sorry for the trouble. if you could share your error message exactly with any details, perhaps i could wrap it in a more useful error message in this package (and suggest you've reached the api limit fro google)?

if what you're using it for is public or open source, perhaps I could recommend a way to avoid reaching the limit? (google has a rate limit for requests that you may be exceeding)

**Comment by hcientist** [comment]
do you have a catch statement for your call to search? perhaps it is giving you some info there?

**Comment by whatwehaveunlearned** [comment]
Yea sure, I will post the message once I get it again. It is not an error its just actually a warning complain because I actually don't catch the error on the promise. I will take it a look later but 100% sure is just blocking me because after a few hours it works again. This happens when I call too many times in a row the API while I am developing. I am actually a PhD student and im using this API to do research work so yeah its open source. I actually use another call for getting images that allows me to specify how many calls per second I can do to google and that way I don't get kicked out. Thank you for your help! :)

**Comment by hcientist** [comment]
updated the package to 1.3.0 to add a bit more support for this issue: 1ecbb01 you should be fine so long as you're sure to have a `catch` statement (not just a `then` statement) for the promise returned by `search` (e.g. https://github.com/VT-CHCI/google-scholar/blob/master/test/test.js#L26 )

**Comment by whatwehaveunlearned** [comment]
Thank you for your help! :)

**Comment by whatwehaveunlearned** [comment]
> if what you're using it for is public or open source, perhaps I could recommend a way to avoid reaching the limit? (google has a rate limit for requests that you may be exceeding) 

If you can and have some time I would appreciate a hint with this.

**Comment by hcientist** [comment]
while we now have amore clear indicator that we've hit the rate limit, we don't really help the user deal with it. perhaps https://github.com/jhurliman/node-rate-limiter is a nice way to help. we can use it internally and implement sane defaults, assuming 5 queries per second and 200 per minute bc https://developers.google.com/webmaster-tools/search-console-api-original/v3/limits

**Comment by hcientist** [comment]
> I am actually a PhD student and im using this API to do research work so yeah its open source.
> ...
> If you can and have some time I would appreciate a hint with this.

@whatwehaveunlearned can you link me to the source? I don't see it in your github?

**Comment by hcientist** [comment]
I will try to utilize https://www.npmjs.com/package/throttled-queue or https://www.npmjs.com/package/bottleneck next (because node-ratelimiter doesn't seem to work and i think https://github.com/eventEmitter/request-rate-limiter didn't either?)
