### ISSUE TITLE
Check if it's you who sends the requests instead of a robot.

### ISSUE THREAD

**Issue by edu526** [VT-CHCI/google-scholar#6]
About this page
Our systems have detected unusual traffic coming from your computer network. This page checks if you are the one sending the requests instead of a robot. What is this about?

GET https://ipv4.google.com/sorry/index?continue= .... 503 ()
ERROR Error: Uncaught (in promise): expected statusCode 200 on http response, but got: 503

**Comment by hcientist** [comment]
looks like i have a bug in detecting when we hit the rate limit. i have an open bug #2 about solving rate limit. you requested too many things from them too quickly.

**Comment by hcientist** [comment]
i'm closing this because i'm pretty sure you're just experiencing #2 also it's beyond the scope of this package to ensure you're protecting your server from outside usage where necessary.
